### ISSUE TITLE
Wiki Editions not working

### ISSUE THREAD

**Issue by Victor-IT** [funktechno/kanboard-plugin-wiki#9]
This issue is:
- [X] Bug report

"There are not editions to restore." message in Wiki Editions
Hovewer "Editions: 3 Current Edition: 3"
Should I change any settings for the plugin to function correctly?

Kanboard version: 1.2.4
PHP version: 7.1.9

**Comment by lastlink** [comment]
What database are you using? The restore function should be working fine.

**Comment by Victor-IT** [comment]
mysql: 5.6.39-83.1

**Comment by lastlink** [comment]
have you already navigated to the editions page?

**Comment by Victor-IT** [comment]
Still not working.
![image](https://user-images.githubusercontent.com/26308124/42963824-fa3d6f72-8b9d-11e8-8797-ba362054027d.png)

**Comment by lastlink** [comment]
This is not a bug @Victor-IT I think you are not currently saving editions. This is a global setting. Go to `?controller=ConfigController&action=index` Then click on **Wiki settings** to turn on saving of editions. Basically if this is on it will save copies every time you make a change. You can restore at any time even if this is off as long as there **were** editions saved.
